<div id="intro-overlay">
      <div class="content-wrapper">
              <h1 class="main-title">COMPLEXO 1</h1>
                      <h2 class="sub-title">DO COMANDO NORTE</h2>
                          </div>
                              <div class="scanline"></div>
                              </div>

                              <style>
                                  @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap');

                                      #intro-overlay {
                                              position: fixed;
                                                      top: 0;
                                                              left: 0;
                                                                      width: 100%;
                                                                              height: 100%;
                                                                                      background: radial-gradient(circle, #1a1a1a 0%, #000 100%);
                                                                                              display: flex;
                                                                                                      align-items: center;
                                                                                                              justify-content: center;
                                                                                                                      z-index: 9999;
                                                                                                                              overflow: hidden;
                                                                                                                                      font-family: 'Archivo Black', sans-serif;
                                                                                                                                              animation: fadeOut 0.8s ease-in forwards 3s; /* Some em 3s */
                                                                                                                                                  }

                                                                                                                                                      .content-wrapper {
                                                                                                                                                              text-align: center;
                                                                                                                                                                      transform: scale(0);
                                                                                                                                                                              animation: zoomIn 1s cubic-bezier(0.17, 0.89, 0.32, 1.49) forwards;
                                                                                                                                                                                  }

                                                                                                                                                                                      .main-title {
                                                                                                                                                                                              font-size: 8vw;
                                                                                                                                                                                                      margin: 0;
                                                                                                                                                                                                              padding: 0;
                                                                                                                                                                                                                      text-transform: uppercase;
                                                                                                                                                                                                                              background: linear-gradient(to bottom, #fff3a0 20%, #ffd700 50%, #8a6d3b 100%);
                                                                                                                                                                                                                                      -webkit-background-clip: text;
                                                                                                                                                                                                                                              -webkit-text-fill-color: transparent;
                                                                                                                                                                                                                                                      filter: drop-shadow(0 0 30px rgba(255, 215, 0, 0.4));
                                                                                                                                                                                                                                                              letter-spacing: -2px;
                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                      .sub-title {
                                                                                                                                                                                                                                                                              font-size: 3vw;
                                                                                                                                                                                                                                                                                      margin: -10px 0 0 0;
                                                                                                                                                                                                                                                                                              color: #00f2ff;
                                                                                                                                                                                                                                                                                                      text-transform: uppercase;
                                                                                                                                                                                                                                                                                                              letter-spacing: 15px;
                                                                                                                                                                                                                                                                                                                      font-style: italic;
                                                                                                                                                                                                                                                                                                                              text-shadow: 0 0 20px rgba(0, 242, 255, 0.8), 0 0 40px rgba(0, 242, 255, 0.4);
                                                                                                                                                                                                                                                                                                                                      animation: pulse 1.5s infinite;
                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                              .scanline {
                                                                                                                                                                                                                                                                                                                                                      position: absolute;
                                                                                                                                                                                                                                                                                                                                                              top: 0; left: 0; width: 100%; height: 100%;
                                                                                                                                                                                                                                                                                                                                                                      background: linear-gradient(rgba(18, 16, 16, 0) 50%, rgba(0, 0, 0, 0.2) 50%),
                                                                                                                                                                                                                                                                                                                                                                                          linear-gradient(90deg, rgba(255,0,0,0.03), rgba(0,255,0,0.01), rgba(0,0,255,0.03));
                                                                                                                                                                                                                                                                                                                                                                                                  background-size: 100% 4px, 3px 100%;
                                                                                                                                                                                                                                                                                                                                                                                                          pointer-events: none;
                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                  /* ANIMAÇÕES */
                                                                                                                                                                                                                                                                                                                                                                                                                      @keyframes zoomIn {
                                                                                                                                                                                                                                                                                                                                                                                                                              0% { transform: scale(0); opacity: 0; filter: brightness(5); }
                                                                                                                                                                                                                                                                                                                                                                                                                                      100% { transform: scale(1); opacity: 1; filter: brightness(1); }
                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                              @keyframes pulse {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      0%, 100% { opacity: 0.6; transform: scale(1); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              50% { opacity: 1; transform: scale(1.02); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      @keyframes fadeOut {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0% { opacity: 1; transform: scale(1); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      100% { opacity: 0; transform: scale(1.5); visibility: hidden; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </style>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Remove o elemento do DOM após a animação para não travar o clique no mapa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const intro = document.getElementById('intro-overlay');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if(intro) intro.style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, 3800);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      