import { Image } from '@/components/ui/image';
import { motion } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';

interface LiveNPCProps {
  src: string;
    alt: string;
      onClick?: () => void;
        className?: string;
          width?: number;
            height?: number;
            }

            export default function LiveNPC({
              src,
                alt,
                  onClick,
                    className = '',
                      width = 400,
                        height = 800,
                        }: LiveNPCProps) {
                          const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
                            const [isHovered, setIsHovered] = useState(false);
                              const [isPressed, setIsPressed] = useState(false);
                                const [blink, setBlink] = useState(false);

                                  const containerRef = useRef<HTMLDivElement>(null);
                                    const blinkTimeoutRef = useRef<NodeJS.Timeout>();
                                      const nextBlinkRef = useRef<NodeJS.Timeout>();

                                        // 👁️ BLINK NATURAL
                                          useEffect(() => {
                                              const scheduleNextBlink = () => {
                                                    const randomDelay = Math.random() * 3000 + 3000;

                                                          nextBlinkRef.current = setTimeout(() => {
                                                                  setBlink(true);

                                                                          blinkTimeoutRef.current = setTimeout(() => {
                                                                                    setBlink(false);
                                                                                              scheduleNextBlink();
                                                                                                      }, 120);
                                                                                                            }, randomDelay);
                                                                                                                };

                                                                                                                    scheduleNextBlink();

                                                                                                                        return () => {
                                                                                                                              if (blinkTimeoutRef.current) clearTimeout(blinkTimeoutRef.current);
                                                                                                                                    if (nextBlinkRef.current) clearTimeout(nextBlinkRef.current);
                                                                                                                                        };
                                                                                                                                          }, []);

                                                                                                                                            // 👀 MOUSE TRACKING SUAVE
                                                                                                                                              useEffect(() => {
                                                                                                                                                  const handleMouseMove = (e: MouseEvent) => {
                                                                                                                                                        if (!containerRef.current) return;

                                                                                                                                                              const rect = containerRef.current.getBoundingClientRect();

                                                                                                                                                                    const centerX = rect.left + rect.width / 2;
                                                                                                                                                                          const centerY = rect.top + rect.height / 2;

                                                                                                                                                                                const deltaX = e.clientX - centerX;
                                                                                                                                                                                      const deltaY = e.clientY - centerY;

                                                                                                                                                                                            const distance = Math.sqrt(deltaX * deltaX + deltaY * deltaY);
                                                                                                                                                                                                  const maxDistance = Math.max(rect.width, rect.height);

                                                                                                                                                                                                        const maxOffset = 5;
                                                                                                                                                                                                              const offset = Math.min((distance / maxDistance) * maxOffset, maxOffset);

                                                                                                                                                                                                                    const dirX = deltaX / distance || 0;
                                                                                                                                                                                                                          const dirY = deltaY / distance || 0;

                                                                                                                                                                                                                                setMousePosition({
                                                                                                                                                                                                                                        x: dirX * offset * 0.4,
                                                                                                                                                                                                                                                y: dirY * offset * 0.4,
                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                              window.addEventListener('mousemove', handleMouseMove);
                                                                                                                                                                                                                                                                  return () => window.removeEventListener('mousemove', handleMouseMove);
                                                                                                                                                                                                                                                                    }, []);

                                                                                                                                                                                                                                                                      // reset mobile
                                                                                                                                                                                                                                                                        useEffect(() => {
                                                                                                                                                                                                                                                                            const handleMouseLeave = () => {
                                                                                                                                                                                                                                                                                  setMousePosition({ x: 0, y: 0 });
                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                          window.addEventListener('mouseleave', handleMouseLeave);
                                                                                                                                                                                                                                                                                              return () => window.removeEventListener('mouseleave', handleMouseLeave);
                                                                                                                                                                                                                                                                                                }, []);

                                                                                                                                                                                                                                                                                                  // 🌬️ RESPIRAÇÃO REAL (SEM ZOOM)
                                                                                                                                                                                                                                                                                                    const breathingVariants = {
                                                                                                                                                                                                                                                                                                        animate: {
                                                                                                                                                                                                                                                                                                              y: [0, -1.5, 0],
                                                                                                                                                                                                                                                                                                                    transition: {
                                                                                                                                                                                                                                                                                                                            duration: 5,
                                                                                                                                                                                                                                                                                                                                    ease: 'easeInOut',
                                                                                                                                                                                                                                                                                                                                            repeat: Infinity,
                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                          const hoverVariants = {
                                                                                                                                                                                                                                                                                                                                                              hover: {
                                                                                                                                                                                                                                                                                                                                                                    scale: 1.05,
                                                                                                                                                                                                                                                                                                                                                                          filter: 'brightness(1.08)',
                                                                                                                                                                                                                                                                                                                                                                                transition: { duration: 0.3 },
                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                        normal: {
                                                                                                                                                                                                                                                                                                                                                                                              scale: 1,
                                                                                                                                                                                                                                                                                                                                                                                                    filter: 'brightness(1)',
                                                                                                                                                                                                                                                                                                                                                                                                          transition: { duration: 0.3 },
                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                  const pressVariants = {
                                                                                                                                                                                                                                                                                                                                                                                                                      press: {
                                                                                                                                                                                                                                                                                                                                                                                                                            scale: 0.97,
                                                                                                                                                                                                                                                                                                                                                                                                                                  transition: { duration: 0.1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                          release: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                scale: isHovered ? 1.05 : 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition: { duration: 0.2 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ref={containerRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="relative"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onMouseEnter={() => setIsHovered(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onMouseLeave={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setIsHovered(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setIsPressed(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onMouseDown={() => setIsPressed(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onMouseUp={() => setIsPressed(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <motion.div variants={breathingVariants} animate="animate">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        variants={hoverVariants}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  animate={isHovered ? 'hover' : 'normal'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                variants={pressVariants}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            animate={isPressed ? 'press' : 'release'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      x: mousePosition.x,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    y: mousePosition.y,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* SOMBRA */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="absolute -bottom-6 left-1/2 -translate-x-1/2 w-3/4 h-6 rounded-full blur-2xl opacity-30"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'radial-gradient(ellipse, rgba(0,0,0,0.4), transparent)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* NPC */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                src={src}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alt={alt}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={onClick}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={`cursor-pointer ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isHovered
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? 'drop-shadow-[0_0_20px_rgba(255,215,0,0.3)]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : 'drop-shadow-lg'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } ${className}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width={width}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height={height}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* BLINK REAL (LOCALIZADO) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {blink && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      initial={{ scaleY: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        animate={{ scaleY: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          transition={{ duration: 0.12, ease: 'easeInOut' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="absolute left-1/2 -translate-x-1/2 pointer-events-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  top: '22%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: '35%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height: '12%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: 'rgba(0,0,0,0.6)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: '50%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transformOrigin: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* GLOW PRESENÇA */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="absolute inset-0 pointer-events-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      animate={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: isHovered
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? '0 0 40px rgba(255,215,0,0.2)'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : '0 0 10px rgba(255,215,0,0.05)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        transition={{ duration: 0.3 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
